export const data = {
  id: 128,
  count_views: null,
  work_type_list: ['increase_the_citation_of_your_works'],
  knowledge_area_list: ['biology_genetics', 'engineering_material', 'physics_astronomy'],
  title: 'string',
  comment: 'string',
  reward_type_list: ['accept_as_coauthors', 'money', 'work_with_text_and_graphics'],
  reward_sum: 0.0,
  reward_currency: null,
  reward_comment: null,
  approx_date: null,
  keyword_list: ['string'],
  whois: 'guest',
  is_profile_visible: true,
  hide_from_other_users: true,
  hide_from_search: true,
  posting_id: null,
  request_type: 'supply',
  offers: [],
  can_review: false,
  user: {
    id: 56,
    profile: {
      id: 4,
      first_name: 'Dan',
      last_name: 'Myasnikov',
      middle_name: '',
      affiliation: '',
      about: '',
      country: '',
      lang: '',
      city: '',
      public_visibility: true,
      affiliation_visibility: null,
      email_notifications: true,
      push_notifications: true,
      created_at: '2021-06-26T15:56:02.070Z',
      updated_at: '2021-08-11T21:23:54.992Z',
      user_id: 56,
      degree: '',
      degree_category: '',
      orcid_uuid: '0000-0003-4254-1799',
      phone_number: null,
      slug: 'dan-myasnikov',
    },
  },
  offer: {
    id: 128,
    count_views: null,
    work_type_list: ['increase_the_citation_of_your_works'],
    knowledge_area_list: ['biology_genetics', 'engineering_material', 'physics_astronomy'],
    title: 'string',
    comment: 'string',
    reward_type_list: ['accept_as_coauthors', 'money', 'work_with_text_and_graphics'],
    reward_sum: 0.0,
    reward_currency: null,
    reward_comment: null,
    approx_date: null,
    keyword_list: ['string'],
    whois: 'guest',
    is_profile_visible: true,
    hide_from_other_users: true,
    hide_from_search: true,
    posting_id: null,
    request_type: 'supply',
    offers: [],
    can_review: false,
    user: {
      id: 56,
      profile: {
        id: 4,
        first_name: 'Dan',
        last_name: 'Myasnikov',
        middle_name: 'middle_name',
        affiliation: 'affiliation',
        about: ' about about about about',
        country: '',
        lang: '',
        city: '',
        public_visibility: true,
        affiliation_visibility: null,
        email_notifications: true,
        push_notifications: true,
        created_at: '2021-06-26T15:56:02.070Z',
        updated_at: '2021-08-11T21:23:54.992Z',
        user_id: 56,
        degree: '',
        degree_category: '',
        orcid_uuid: '0000-0003-4254-1799',
        phone_number: null,
        slug: 'dan-myasnikov',
      },
    },
  },
};
