export const STATUS_OPTIONS = [
    { value: 'scientist', label: 'Учёный' },
    { value: 'student', label: 'Обучающийся' },
    { value: 'organization', label: 'Организация' },
    { value: 'other', label: 'Сторонний' },
  ];
  
  export const STUDENT_OPTIONS = [
    { value: 'Школьник', label: 'Школьник' },
    { value: 'Студент', label: 'Студент' },
    { value: 'Аспирант', label: 'Аспирант' },
  ];
  
  export const GRADE_OPTIONS = [
    { value: 'к.т.н', label: 'к.т.н' },
    { value: ' к.т.н., доц.', label: ' к.т.н., доц.' },
    { value: 'д.т.н', label: 'д.т.н' },
    { value: 'д.т.н., проф.', label: 'д.т.н., проф.' },
  ];
  
  export const COUNTRIES =[
      { value:"AF", label:'Afghanistan'},
      { value:"AL", label:'Albania'},
      { value:"DZ", label:'Algeria'},
      { value:"AS", label:'American Samoa'},
      { value:"AD", label:'Andorra'},
      { value:"AO", label:'Angola'},
      { value:"AI", label:'Anguilla'},
      { value:"AQ", label:'Antarctica'},
      { value:"AG", label:'Antigua and Barbuda'},
      { value:"AR", label:'Argentina'},
      { value:"AM", label:'Armenia'},
      { value:"AW", label:'Aruba'},
      { value:"AU", label:'Australia'},
      { value:"AT", label:'Austria'},
      { value:"AZ", label:'Azerbaijan'},
      { value:"BS", label:'Bahamas'},
      { value:"BH", label:'Bahrain'},
      { value:"BD", label:'Bangladesh'},
      { value:"BB", label:'Barbados'},
      { value:"BY", label:'Belarus'},
      { value:"BE", label:'Belgium'},
      { value:"BZ", label:'Belize'},
      { value:"BJ", label:'Benin'},
      { value:"BM", label:'Bermuda'},
      { value:"BT", label:'Bhutan'},
      { value:"BO", label:'Bolivia'},
      { value:"BA", label:'Bosnia and Herzegovina'},
      { value:"BW", label:'Botswana'},
      { value:"BV", label:'Bouvet Island'},
      { value:"BR", label:'Brazil'},
      { value:"IO", label:'British Indian Ocean Territory'},
      { value:"BN", label:'Brunei Darussalam'},
      { value:"BG", label:'Bulgaria'},
      { value:"BF", label:'Burkina Faso'},
      { value:"BI", label:'Burundi'},
      { value:"CV", label:'Cabo Verde'},
      { value:"KH", label:'Cambodia'},
      { value:"CM", label:'Cameroon'},
      { value:"CA", label:'Canada'},
      { value:"CV", label:'Cape Verde'},
      { value:"KY", label:'Cayman Islands'},
      { value:"CF", label:'Central African Republic'},
      { value:"TD", label:'Chad'},
      { value:"CL", label:'Chile'},
      { value:"CN", label:'China'},
      { value:"CX", label:'Christmas Island'},
      { value:"CO", label:'Colombia'},
      { value:"KM", label:'Comoros'},
      { value:"CG", label:'Congo'},
      { value:"CK", label:'Cook Islands'},
      { value:"CR", label:'Costa Rica'},
      { value:"CI", label:'Cote d`Ivoire'},
      { value:"CU", label:'Cuba'},
      { value:"CY", label:'Cyprus'},
      { value:"CZ", label:'Czech Republic'},
      { value:"DK", label:'Denmark'},
      { value:"DJ", label:'Djibouti'},
      { value:"DM", label:'Dominica'},
      { value:"DO", label:'Dominican Republic'},
      { value:"EC", label:'Ecuador'},
      { value:"EG", label:'Egypt'},
      { value:"SV", label:'El Salvador'},
      { value:"GQ", label:'Equatorial Guinea'},
      { value:"ER", label:'Eritrea'},
      { value:"EE", label:'Estonia'},
      { value:"SZ", label:'Eswatini'},
      { value:"ET", label:'Ethiopia'},
      { value:"FK", label:'Falkland Islands'},
      { value:"FO", label:'Faroe Islands'},
      { value:"FJ", label:'Fiji'},
      { value:"FI", label:'Finland'},
      { value:"FR", label:'France'},
      { value:"GF", label:'French Guiana'},
      { value:"PF", label:'French Polynesia'},
      { value:"TF", label:'French Southern Territories'},
      { value:"GA", label:'Gabon'},
      { value:"GM", label:'Gambia'},
      { value:"GE", label:'Georgia'},
      { value:"DE", label:'Germany'},
      { value:"GH", label:'Ghana'},
      { value:"GI", label:'Gibraltar'},
      { value:"GR", label:'Greece'},
      { value:"GL", label:'Greenland'},
      { value:"GD", label:'Grenada'},
      { value:"GP", label:'GUADELOUPE'},
      { value:"GU", label:'GUAM'},
      { value:"GT", label:'GUATEMALA'},
      { value:"GN", label:'GUINEA'},
      { value:"GW", label:'GUINEA-BISSAU'},
      { value:"GY", label:'GUYANA'},
      { value:"HT", label:'HAITI'},
      { value:"HM", label:'HEARD AND MC DONALD ISLANDS'},
      { value:"HN", label:'HONDURAS'},
      { value:"HK", label:'HONG KONG'},
      { value:"HU", label:'HUNGARY'},
      { value:"IS", label:'ICELAND'},
      { value:"IN", label:'INDIA'},
      { value:"ID", label:'INDONESIA'},
      { value:"IQ", label:'IRAQ'},
      { value:"IE", label:'IRELAND'},
      { value:"IL", label:'ISRAEL'},
      { value:"IT", label:'ITALY'},
      { value:"JM", label:'JAMAICA'},
      { value:"JP", label:'JAPAN'},
      { value:"JO", label:'JORDAN'},
      { value:"KZ", label:'KAZAKHSTAN'},
      { value:"KE", label:'KENYA'},
      { value:"KI", label:'KIRIBATI'},
      { value:"KW", label:'KUWAIT'},
      { value:"KG", label:'KYRGYZSTAN'},
      { value:"LA", label:'LAO PEOPLE`S DEMOCRATIC REPUBLIC'},
      { value:"LV", label:'LATVIA'},
      { value:"LB", label:'LEBANON'},
      { value:"LS", label:'LESOTHO'},
      { value:"LR", label:'LIBERIA'},
      { value:"LY", label:'LIBYAN ARAB JAMAHIRIYA'},
      { value:"LI", label:'LIECHTENSTEIN'},
      { value:"LT", label:'LITHUANIA'},
      { value:"LU", label:'LUXEMBOURG'},
      { value:"MO", label:'MACAU'},
      { value:"MG", label:'MADAGASCAR'},
      { value:"MW", label:'MALAWI'},
      { value:"MY", label:'MALAYSIA'},
      { value:"MV", label:'MALDIVES'},
      { value:"ML", label:'MALI'},
      { value:"MT", label:'MALTA'},
      { value:"MH", label:'MARSHALL ISLANDS'},
      { value:"MQ", label:'MARTINIQUE'},
      { value:"MR", label:'MAURITANIA'},
      { value:"MU", label:'MAURITIUS'},
      { value:"YT", label:'MAYOTTE'},
      { value:"MX", label:'MEXICO'},
      { value:"MC", label:'MONACO'},
      { value:"MN", label:'MONGOLIA'},
      { value:"MS", label:'MONTSERRAT'},
      { value:"MA", label:'MOROCCO'},
      { value:"MZ", label:'MOZAMBIQUE'},
      { value:"MM", label:'MYANMAR'},
      { value:"NA", label:'NAMIBIA'},
      { value:"NR", label:'NAURU'},
      { value:"NP", label:'NEPAL'},
      { value:"NL", label:'NETHERLANDS'},
      { value:"AN", label:'NETHERLANDS ANTILLES'},
      { value:"NC", label:'NEW CALEDONIA'},
      { value:"NZ", label:'NEW ZEALAND'},
      { value:"NI", label:'NICARAGUA'},
      { value:"NE", label:'NIGER'},
      { value:"NG", label:'NIGERIA'},
      { value:"NU", label:'NIUE'},
      { value:"NF", label:'NORFOLK ISLAND'},
      { value:"MP", label:'NORTHERN MARIANA ISLANDS'},
      { value:"NO", label:'NORWAY'},
      { value:"OM", label:'OMAN'},
      { value:"PK", label:'PAKISTAN'},
      { value:"PW", label:'PALAU'},
      { value:"PA", label:'PANAMA'},
      { value:"PG", label:'PAPUA NEW GUINEA'},
      { value:"PY", label:'PARAGUAY'},
      { value:"PE", label:'PERU'},
      { value:"PH", label:'PHILIPPINES'},
      { value:"PN", label:'PITCAIRN'},
      { value:"PL", label:'POLAND'},
      { value:"PT", label:'PORTUGAL'},
      { value:"PR", label:'PUERTO RICO'},
      { value:"QA", label:'QATAR'},
      { value:"RE", label:'REUNION'},
      { value:"RO", label:'ROMANIA'},
      { value:"RU", label:'RUSSIAN FEDERATION'},
      { value:"RW", label:'RWANDA'},
      { value:"SH", label:'SAINT HELENA'},
      { value:"KN", label:'SAINT KITTS AND NEVIS'},
      { value:"LC", label:'SAINT LUCIA'},
      { value:"PM", label:'SAINT PIERRE AND MIQUELON'},
      { value:"VC", label:'SAINT VINCENT AND THE GRENADINES'},
      { value:"WS", label:'SAMOA'},
      { value:"SM", label:'SAN MARINO'},
      { value:"ST", label:'SAO TOME AND PRINCIPE'},
      { value:"SA", label:'SAUDI ARABIA'},
      { value:"SN", label:'SENEGAL'},
      { value:"CS", label:'SERBIA AND MONTENEGRO'},
      { value:"SC", label:'SEYCHELLES'},
      { value:"SL", label:'SIERRA LEONE'},
      { value:"SG", label:'SINGAPORE'},
      { value:"SK", label:'SLOVAKIA'},
      { value:"SI", label:'SLOVENIA'},
      { value:"SB", label:'SOLOMON ISLANDS'},
      { value:"SO", label:'SOMALIA'},
      { value:"ZA", label:'SOUTH AFRICA'},
      { value:"GS", label:'SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS'},
      { value:"ES", label:'SPAIN'},
      { value:"LK", label:'SRI LANKA'},
      { value:"SD", label:'SUDAN'},
      { value:"SR", label:'SURINAME'},
      { value:"SJ", label:'SVALBARD AND JAN MAYEN ISLANDS'},
      { value:"SZ", label:'SWAZILAND'},
      { value:"SE", label:'SWEDEN'},
      { value:"CH", label:'SWITZERLAND'},
      { value:"SY", label:'SYRIAN ARAB REPUBLIC'},
      { value:"TW", label:'TAIWAN'},
      { value:"TJ", label:'TAJIKISTAN'},
      { value:"TH", label:'THAILAND'},
      { value:"TL", label:'TIMOR-LESTE'},
      { value:"TG", label:'TOGO'},
      { value:"TK", label:'TOKELAU'},
      { value:"TO", label:'TONGA'},
      { value:"TT", label:'TRINIDAD AND TOBAGO'},
      { value:"TN", label:'TUNISIA'},
      { value:"TR", label:'TURKEY'},
      { value:"TM", label:'TURKMENISTAN'},
      { value:"TC", label:'TURKS AND CAICOS ISLANDS'},
      { value:"TV", label:'TUVALU'},
      { value:"UG", label:'UGANDA'},
      { value:"UA", label:'UKRAINE'},
      { value:"AE", label:'UNITED ARAB EMIRATES'},
      { value:"GB", label:'UNITED KINGDOM'},
      { value:"US", label:'UNITED STATES'},
      { value:"UM", label:'UNITED STATES MINOR OUTLYING ISLANDS'},
      { value:"UY", label:'URUGUAY'},
      { value:"UZ", label:'UZBEKISTAN'},
      { value:"VU", label:'VANUATU'},
      { value:"VE", label:'VENEZUELA'},
      { value:"VN", label:'VIET NAM'},
      { value:"WF", label:'WALLIS AND FUTUNA ISLANDS'},
      { value:"EH", label:'WESTERN SAHARA'},
      { value:"YE", label:'YEMEN'},
      { value:"ZM", label:'ZAMBIA'},
      { value:"ZW", label:'ZIMBABWE'},
  ]