export const cards = [
  {
    approx_date: "2021-08-01",
    comment: "Some string with random text",
    count_views: 0,
    id: 23,
    keyword_list: "string;string1",
    knowledge_area: "biology",
    poster: {id: 2, first_name: null, last_name: null, middle_name: null, about: null, country: null, lang: null},
    revert_posting: {work_type: "become_coathor", knowledge_area: "biology", title: "Title #1. So it's about this."},
    reward_comment: "",
    reward_currency: "",
    reward_sum: null,
    reward_type: "",
    secreted: false,
    title: "Вопросы проектирования трансатлантического межнационального продуктопровода в условиях нарастающей коронавирусной пандемии",
    work_type: null
  },
  {
    approx_date: "2021-08-01",
    comment: "Some string with random text",
    count_views: 0,
    id: 21,
    keyword_list: "string;string1",
    knowledge_area: "biology",
    poster: {id: 2, first_name: null, last_name: null, middle_name: null, about: null, country: null, lang: null},
    revert_posting: {work_type: "become_coathor", knowledge_area: "biology", title: "Title #1. So it's about this."},
    reward_comment: null,
    reward_currency: null,
    reward_sum: 500,
    reward_type: "return_help",
    secreted: true,
    title: "Title #0. So it's about that",
    work_type: "invite_coathor",
  },
  {
    approx_date: "2021-08-01",
    comment: "Some string with random text",
    count_views: 0,
    id: 2,
    keyword_list: "string;string1",
    knowledge_area: "biology",
    poster: {id: 2, first_name: null, last_name: null, middle_name: null, about: null, country: null, lang: null},
    revert_posting: {work_type: "become_coathor", knowledge_area: "biology", title: "Title #1. So it's about this."},
    reward_comment: null,
    reward_currency: null,
    reward_sum: 500,
    reward_type: "return_help",
    secreted: true,
    title: "Title #0. So it's about that",
    work_type: "invite_coathor",
  },
  {
    approx_date: "2021-08-01",
    comment: "Some string with random text",
    count_views: 0,
    id: 3,
    keyword_list: "string;string1",
    knowledge_area: "biology",
    poster: {id: 2, first_name: null, last_name: null, middle_name: null, about: null, country: null, lang: null},
    revert_posting: {work_type: "become_coathor", knowledge_area: "biology", title: "Title #1. So it's about this."},
    reward_comment: null,
    reward_currency: null,
    reward_sum: 500,
    reward_type: "return_help",
    secreted: true,
    title: "Title #0. So it's about that",
    work_type: "invite_coathor",
  },
];
